{
 "title": "TP5 - Application Monitoring",
 "tags": [
  "TP5",
  "Prometheus",
  "DevOps"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Requests / second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(http_requests_total[1m]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total[1m]))",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  {
   "title": "HTTP Latency P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, endpoint) (rate(http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Targets UP",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "sum(up)" }
   ]
  }
 ]
}